import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-800">
      <header className="w-full max-w-4xl mx-auto px-6 sm:px-8 py-6 flex items-center justify-between">
        <Link href="/" className="flex items-center">
          <img src="/Blue White Professional Minimal Company Business Card.png" alt="TASKEZY" className="h-8 w-auto object-contain" />
        </Link>
        <Link href="/auth/login" className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-600 hover:text-brand-700 transition-colors">
          <ArrowLeft className="h-3.5 w-3.5" /> Back to Sign In
        </Link>
      </header>

      <main className="max-w-4xl mx-auto px-6 sm:px-8 pb-24">
        <div className="bg-white border border-slate-200 rounded-2xl shadow-sm p-8 sm:p-12 space-y-8">
          <div>
            <h1 className="text-2xl font-extrabold text-brand-700">Terms of Service</h1>
            <p className="text-xs text-slate-450 mt-1">Last updated: August 2026 · Realhubb Ventures Private Limited</p>
          </div>

          <p className="text-sm text-slate-600 leading-relaxed">
            These terms govern access to and use of the TASKEZY platform, an internal enterprise system operated by
            Realhubb Ventures Private Limited for its own CRM, HRMS, and Finance operations.
          </p>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-800">1. Authorized Use</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              Access to TASKEZY is provisioned per-user by an Administrator and is restricted to employees and
              authorized representatives of Realhubb Ventures Private Limited. Login credentials are personal and must
              not be shared. Each user&apos;s actions within the platform (lead updates, reassignments, financial entries)
              are attributed to their account and logged for accountability.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-800">2. Role-Based Access</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              The platform enforces role-based permissions (Admin, Manager, Sales Agent, Finance). A user may only view
              or act on data their role permits — for example, a Sales Agent may only see their own assigned leads
              unless granted broader access. Attempting to circumvent these restrictions, including by direct API
              access outside the application UI, is prohibited.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-800">3. Data Accuracy</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              Users are responsible for the accuracy of data they enter, including lead status updates, deal values,
              KYC verification, and invoice details. Financial records generated by the platform (invoice numbers, GST
              calculations) are derived from user-entered figures and should be verified before being issued externally.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-800">4. Third-Party Integrations</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              TASKEZY connects to Meta (Facebook/Instagram) and Google Ads to ingest leads and campaign spend data.
              Use of these integrations is subject to each platform&apos;s own terms of service in addition to these terms.
              Realhubb Ventures is responsible for maintaining valid, authorized connections to these third-party
              accounts.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-800">5. Availability</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              The platform is provided on an as-is, as-available basis for internal operational use. While reasonable
              efforts are made to keep the system available and data accurate, Realhubb Ventures does not guarantee
              uninterrupted access and is not liable for business decisions made based on platform data without
              independent verification.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-800">6. Account Termination</h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              Access may be revoked by an Administrator at any time, including upon an employee&apos;s departure from the
              company or a violation of these terms. Historical records created by a deactivated account remain in the
              system for business continuity and compliance purposes.
            </p>
          </section>

          <p className="text-[11px] text-slate-400 italic border-t border-slate-100 pt-4">
            This document describes the platform&apos;s intended terms of use and is provided for internal transparency. It
            is not a substitute for formal legal counsel — a fully reviewed, legally binding version should be published
            before this platform is used with any party outside Realhubb Ventures.
          </p>
        </div>
      </main>
    </div>
  );
}
